// 飞船配置数据 (9艘飞船)
import { ShipConfig } from '../types';

// 默认模型URL，从 R2 CDN 加载
const DEFAULT_MODEL_URL = 'https://pub-ef918f4135654b1caa2833736c639ae1.r2.dev/eve-ss-empire-eve/models/ship_optimized.glb';

export const SHIP_CONFIGS: Record<string, ShipConfig> = {
  // ========== 艾玛帝国 (Amarr Empire) ==========
  'imperial': {
    id: 'imperial',
    name: 'Imperial Issue',
    chineseName: '帝国号',
    class: 'Battleship',
    manufacturer: 'Amarr Empire',
    faction: 'amarr',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Imperial Issue",
      class: "Battleship",
      manufacturer: "Amarr Empire",
      mass: "98,500,000 kg",
      shield: 6800,
      armor: 8500,
      structure: 7200,
      capacitor: 5800,
      cpu: "645",
      powerGrid: "18500",
      turretSlots: 8,
      launcherSlots: 0,
    }
  },
  'paladin': {
    id: 'paladin',
    name: 'Paladin',
    chineseName: '先锋者级',
    class: 'Marauder',
    manufacturer: 'Amarr Empire',
    faction: 'amarr',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Paladin",
      class: "Marauder",
      manufacturer: "Amarr Empire",
      mass: "115,000,000 kg",
      shield: 5200,
      armor: 9800,
      structure: 8500,
      capacitor: 6500,
      cpu: "750",
      powerGrid: "22000",
      turretSlots: 4,
      launcherSlots: 0,
    }
  },
  'avatar': {
    id: 'avatar',
    name: 'Avatar',
    chineseName: '神使级泰坦',
    class: 'Titan',
    manufacturer: 'Amarr Empire',
    faction: 'amarr',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.5,
    stats: {
      name: "Avatar",
      class: "Titan",
      manufacturer: "Amarr Empire",
      mass: "2,400,000,000 kg",
      shield: 250000,
      armor: 400000,
      structure: 350000,
      capacitor: 125000,
      cpu: "1250",
      powerGrid: "750000",
      turretSlots: 6,
      launcherSlots: 0,
    }
  },

  // ========== 加达里合众国 (Caldari State) ==========
  'naga': {
    id: 'naga',
    name: 'Naga',
    chineseName: '娜迦级',
    class: 'Battlecruiser',
    manufacturer: 'Caldari State',
    faction: 'caldari',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Naga",
      class: "Battlecruiser",
      manufacturer: "Caldari State",
      mass: "18,500,000 kg",
      shield: 4200,
      armor: 2800,
      structure: 3500,
      capacitor: 2200,
      cpu: "435",
      powerGrid: "9200",
      turretSlots: 8,
      launcherSlots: 0,
    }
  },
  'cerberus': {
    id: 'cerberus',
    name: 'Cerberus',
    chineseName: '希尔博拉斯',
    class: 'Heavy Assault Cruiser',
    manufacturer: 'Caldari State',
    faction: 'caldari',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Cerberus",
      class: "Heavy Assault Cruiser",
      manufacturer: "Caldari State",
      mass: "12,850,000 kg",
      shield: 3800,
      armor: 2200,
      structure: 2900,
      capacitor: 1950,
      cpu: "385",
      powerGrid: "7500",
      turretSlots: 0,
      launcherSlots: 5,
    }
  },
  'corax': {
    id: 'corax',
    name: 'Corax',
    chineseName: '渡鸦级',
    class: 'Destroyer',
    manufacturer: 'Caldari State',
    faction: 'caldari',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Corax",
      class: "Destroyer",
      manufacturer: "Caldari State",
      mass: "1,480,000 kg",
      shield: 950,
      armor: 550,
      structure: 680,
      capacitor: 580,
      cpu: "195",
      powerGrid: "48",
      turretSlots: 0,
      launcherSlots: 7,
    }
  },

  // ========== 盖伦特联邦 (Gallente Federation) ==========
  'tristan': {
    id: 'tristan',
    name: 'Tristan',
    chineseName: '特里斯坦',
    class: 'Frigate',
    manufacturer: 'Gallente Federation',
    faction: 'gallente',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Tristan",
      class: "Frigate",
      manufacturer: "Gallente Federation",
      mass: "1,180,000 kg",
      shield: 420,
      armor: 580,
      structure: 520,
      capacitor: 380,
      cpu: "160",
      powerGrid: "38",
      turretSlots: 3,
      launcherSlots: 2,
    }
  },
  'thalia': {
    id: 'thalia',
    name: 'Thalia',
    chineseName: '塔利亚',
    class: 'Logistics Frigate',
    manufacturer: 'Gallente Federation',
    faction: 'gallente',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Thalia",
      class: "Logistics Frigate",
      manufacturer: "Gallente Federation",
      mass: "1,350,000 kg",
      shield: 580,
      armor: 680,
      structure: 550,
      capacitor: 950,
      cpu: "185",
      powerGrid: "42",
      turretSlots: 2,
      launcherSlots: 0,
    }
  },
  'atron': {
    id: 'atron',
    name: 'Atron',
    chineseName: '阿特龙级',
    class: 'Interceptor',
    manufacturer: 'Gallente Federation',
    faction: 'gallente',
    modelPath: DEFAULT_MODEL_URL,
    scale: 1.0,
    stats: {
      name: "Atron",
      class: "Interceptor",
      manufacturer: "Gallente Federation",
      mass: "980,000 kg",
      shield: 380,
      armor: 520,
      structure: 480,
      capacitor: 350,
      cpu: "150",
      powerGrid: "35",
      turretSlots: 3,
      launcherSlots: 0,
    }
  },
};

// 默认飞船（如果URL参数无效）
export const DEFAULT_SHIP_ID = 'imperial';
